"""
Database configuration and SQLAlchemy models for FitBuddy.
Uses SQLite for lightweight, serverless persistence.
"""

import os
from datetime import datetime
from typing import Generator
from sqlalchemy import create_engine, Column, Integer, String, Float, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import declarative_base, sessionmaker, relationship, Session

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./fitbuddy.sqlite")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class User(Base):
    """Stores athlete demographic parameters and credentials."""
    __tablename__ = "users"

    id = Column(String(64), primary_key=True, index=True)  # User ID (e.g. USR-101)
    name = Column(String(128), nullable=False)
    age = Column(Integer, nullable=False)
    weight = Column(Float, nullable=False)  # in kg
    fitness_goal = Column(String(64), nullable=False)  # Weight Loss, Muscle Gain, General Fitness, Flexibility
    workout_intensity = Column(String(32), nullable=False)  # Low, Medium, High
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    plans = relationship("WorkoutPlan", back_populates="user", cascade="all, delete-orphan")

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "age": self.age,
            "weight": self.weight,
            "fitness_goal": self.fitness_goal,
            "workout_intensity": self.workout_intensity,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M:%S") if self.created_at else None,
        }


class WorkoutPlan(Base):
    """
    Stores original workout plans generated by Gemini 1.5 Pro,
    the Gemini Flash nutrition tip, user feedback, and updated plans.
    """
    __tablename__ = "workout_plans"

    id = Column(String(64), primary_key=True, index=True)
    user_id = Column(String(64), ForeignKey("users.id"), nullable=False, index=True)
    version = Column(Integer, default=1)
    is_original = Column(Boolean, default=True)
    plan_title = Column(String(256), nullable=False)
    original_plan = Column(Text, nullable=False)  # Full 7-Day original workout plan text or JSON
    updated_plan = Column(Text, nullable=True)   # Updated plan text or JSON generated via feedback
    nutrition_tip = Column(Text, nullable=True)  # Gemini Flash generated nutrition/recovery tip
    feedback = Column(Text, nullable=True)       # User feedback (e.g., "Add more cardio", "Add yoga")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = relationship("User", back_populates="plans")

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "version": self.version,
            "is_original": self.is_original,
            "plan_title": self.plan_title,
            "original_plan": self.original_plan,
            "updated_plan": self.updated_plan,
            "nutrition_tip": self.nutrition_tip,
            "feedback": self.feedback,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%M:%S") if self.created_at else None,
            "updated_at": self.updated_at.strftime("%Y-%m-%d %H:%M:%S") if self.updated_at else None,
        }


def init_db():
    """Initializes the database schema and seeds initial sample records."""
    Base.metadata.create_all(bind=engine)
    seed_demo_data()


def get_db() -> Generator[Session, None, None]:
    """Dependency generator for database sessions in FastAPI."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def seed_demo_data():
    """Seeds sample athlete records if the database is empty."""
    db = SessionLocal()
    try:
        count = db.query(User).count()
        if count == 0:
            user1 = User(
                id="USR-101",
                name="Alex Rivera",
                age=27,
                weight=74.0,
                fitness_goal="Muscle Gain",
                workout_intensity="Medium"
            )
            db.add(user1)
            db.commit()

            plan1 = WorkoutPlan(
                id="PLAN-USR-101-V1",
                user_id="USR-101",
                version=2,
                is_original=False,
                plan_title="7-Day Muscle Hypertrophy & Kinetic Conditioning",
                original_plan="""Day 1: Chest & Triceps (Bench Press 4x8, Incline DB Press 3x10, Dips 3x12)
Warm-up: 5m arm circles & band pull-aparts.
Cool-down: Doorway pec stretch & triceps overhead stretch.

Day 2: Back & Biceps (Barbell Rows 4x8, Pull-ups 3x8, Hammer Curls 3x12)
Warm-up: Cat-cow and lat sweeps.
Cool-down: Child's pose and kneeling lat stretches.

Day 3: Legs & Core (Squats 4x8, Romanian Deadlifts 3x10, Walking Lunges 3x12, Planks 3x60s)
Warm-up: Hip openers & leg swings.
Cool-down: Hamstring and piriformis stretch.

Day 4: Shoulders & Abs (Overhead Press 4x8, Lateral Raises 4x12, Hanging Knee Raises 3x15)
Warm-up: Arm rotations & shoulder dislocates.
Cool-down: Cross-body shoulder stretch.

Day 5: Full Body Power (Deadlifts 3x5, DB Clean & Press 3x8, Goblet Squats 3x12)
Warm-up: Dynamic full body activation.
Cool-down: World's greatest stretch.

Day 6: HIIT & Core Conditioning (Kettlebell Swings 4x15, Mountain Climbers 4x30s, Bicycle Crunches 3x20)
Warm-up: Jumping jacks and high knees.
Cool-down: Cobra stretch and seated forward bend.

Day 7: Active Recovery (30-minute brisk outdoor walk + full-body mobility)
Warm-up: Gentle dynamic rotations.
Cool-down: Foam rolling lats, glutes, and quads.""",
                updated_plan="""Day 1: Chest & Triceps + 10m Incline Walk Cardio
Day 2: Back & Biceps + 10m Rowing Machine
Day 3: Rest & Core Mobility
Day 4: Rest & Hydration
Day 5: Shoulders & Arms Hypertrophy
Day 6: Lower Body Focus (Goblet Squats & Lunges)
Day 7: 45-Minute Restorative Vinyasa Yoga & Breathwork Flow""",
                nutrition_tip="Consume 30-40g high-quality whey or lean poultry with 60g complex carbohydrates within 45 minutes of training. Hydrate with 3.2L water daily.",
                feedback="Add more cardio and include yoga on the weekend."
            )
            db.add(plan1)
            db.commit()
    except Exception as e:
        db.rollback()
        print("Database seed error:", e)
    finally:
        db.close()
