import { FitnessPlan, UserProfile, WorkoutHistoryLog, WorkoutDay } from '../types.ts';

export const DEFAULT_USER_PROFILE: UserProfile = {
  id: 'user-default',
  name: 'Alex Rivera',
  email: 'alex.rivera@fitbuddy.ai',
  age: 27,
  gender: 'male',
  weightKg: 74,
  heightCm: 178,
  fitnessLevel: 'intermediate',
  primaryGoal: 'muscle_gain',
  workoutIntensity: 'moderate',
  availableTimeMinutes: 45,
  workoutPreference: 'strength_hypertrophy',
  equipment: ['Dumbbells', 'Barbell', 'Pull-up Bar', 'Bench'],
  daysPerWeek: 7,
  preferredDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  injuriesOrRestrictions: 'Mild left shoulder impingement (avoid excessive behind-the-neck pressing)',
  experienceNotes: 'Consistent gym training for 1.5 years, looking for focused progressive overload and core stability.',
};

const DEFAULT_WARMUP = [
  {
    name: 'Dynamic Arm Circles & Chest Hugs',
    duration: '60 seconds',
    description: 'Controlled multidirectional shoulder rotations followed by dynamic chest openers.',
    cues: ['Keep ribcage depressed', 'Reach tall through the crown of the head', 'Active scapular gliding'],
  },
  {
    name: 'World’s Greatest Stretch',
    duration: '90 seconds',
    description: 'Deep lunge with thoracic spine rotation and hamstring extension.',
    cues: ['Elbow sinks toward instep', 'Rotate chest up to the sky', 'Squeeze trailing glute'],
  },
  {
    name: 'Band Pull-Aparts & Wall Slides',
    duration: '60 seconds',
    description: 'Strengthens lower traps and posterior deltoids for shoulder joint longevity.',
    cues: ['Pull with mid-back, not arms', 'Avoid shrugging shoulders up to ears'],
  },
  {
    name: 'Inchworm to Plank Walkout',
    duration: '60 seconds',
    description: 'Activates core, serratus anterior, and posterior chain.',
    cues: ['Hips remain steady with minimal sway', 'Pause in firm plank for 2 seconds'],
  },
];

const DEFAULT_COOLDOWN = [
  {
    name: 'Doorway Pec & Bicep Stretch',
    duration: '60 seconds / side',
    description: 'Decompresses anterior shoulder capsule and pectoralis minor.',
    cues: ['Step through doorway gently until mild stretch in chest', 'Breathe smoothly into diaphragm'],
  },
  {
    name: 'Kneeling Lat & Triceps Stretch',
    duration: '60 seconds',
    description: 'Elbows on bench or floor with palms together, sinking hips back to stretch lats.',
    cues: ['Gently bend elbows behind head', 'Exhale and drop chest toward floor'],
  },
  {
    name: 'Supine Figure-4 Piriformis Stretch',
    duration: '60 seconds / side',
    description: 'Releases deep hip external rotators, gluteus medius, and reduces lower back tension.',
    cues: ['Ankle crossed over opposite knee', 'Gently draw hamstring toward chest'],
  },
];

const SEVEN_DAYS_WORKOUTS: WorkoutDay[] = [
  {
    dayNumber: 1,
    dayName: 'Day 1 - Upper Body Push & Strength',
    title: 'Chest, Anterior Deltoids & Triceps Overload',
    focusArea: 'Pectorals, Anterior/Lateral Delts, Triceps Brachii',
    estimatedDurationMinutes: 45,
    difficulty: 'Moderate',
    isRestDay: false,
    warmUp: DEFAULT_WARMUP.slice(0, 2),
    coolDown: DEFAULT_COOLDOWN.slice(0, 2),
    exercises: [
      {
        id: 'd1-ex1',
        name: 'Incline Dumbbell Bench Press',
        targetMuscles: ['Clavicular Pectoralis Major', 'Anterior Deltoid', 'Triceps'],
        sets: 3,
        reps: '8-10',
        restSeconds: 90,
        tempo: '3-0-1-0',
        equipment: 'Dumbbells & Adjustable Bench',
        formCues: [
          'Set incline to 30 degrees to minimize shoulder impingement',
          'Retract and depress shoulder blades firmly against the pad',
          'Tuck elbows at 45 degrees relative to torso',
        ],
        substitutions: ['Flat Dumbbell Press', 'Floor Dumbbell Press'],
        safetyWarning: 'Do not bounce dumbbells at the bottom; pause with controlled tension.',
      },
      {
        id: 'd1-ex2',
        name: 'Standing Dumbbell Overhead Press (Neutral Grip)',
        targetMuscles: ['Anterior & Lateral Deltoids', 'Core Stabilizers'],
        sets: 3,
        reps: '10-12',
        restSeconds: 75,
        tempo: '2-0-1-0',
        equipment: 'Dumbbells',
        formCues: [
          'Palms facing each other (neutral grip) to protect shoulder impingement',
          'Lock glutes and brace abdominal wall to prevent hyperextending lumbar spine',
          'Press directly overhead until biceps are aligned with ears',
        ],
        substitutions: ['Seated Dumbbell Shoulder Press', 'Half-Kneeling Landmine Press'],
      },
      {
        id: 'd1-ex3',
        name: 'Dumbbell Incline Chest Flyes to Hex Press',
        targetMuscles: ['Sternal Pectoralis', 'Serratus Anterior'],
        sets: 3,
        reps: '12',
        restSeconds: 60,
        tempo: '3-1-1-0',
        equipment: 'Dumbbells',
        formCues: [
          'Maintain a soft 15-degree bend at the elbows throughout arc',
          'Squeeze dumbbells together at peak contraction',
        ],
        substitutions: ['Cable Chest Flyes', 'Push-ups with slow tempo'],
      },
      {
        id: 'd1-ex4',
        name: 'Overhead Dumbbell Triceps Extension',
        targetMuscles: ['Triceps Long Head'],
        sets: 3,
        reps: '12-15',
        restSeconds: 60,
        tempo: '3-0-1-0',
        equipment: 'Single Dumbbell',
        formCues: ['Keep elbows tucked inward, pointing forward', 'Full stretch behind head without overarching lower back'],
        substitutions: ['Dumbbell Skull Crushers', 'Bench Dips'],
      },
    ],
  },
  {
    dayNumber: 2,
    dayName: 'Day 2 - Lower Body Quad & Posterior Chain',
    title: 'Squat Mastery & Posterior Chain Power',
    focusArea: 'Quadriceps, Hamstrings, Gluteus Maximus, Calves',
    estimatedDurationMinutes: 45,
    difficulty: 'Challenging',
    isRestDay: false,
    warmUp: DEFAULT_WARMUP.slice(1, 3),
    coolDown: DEFAULT_COOLDOWN.slice(1, 3),
    exercises: [
      {
        id: 'd2-ex1',
        name: 'Goblet Squat (Heels Elevated)',
        targetMuscles: ['Quadriceps', 'Gluteus Maximus', 'Core'],
        sets: 4,
        reps: '8-10',
        restSeconds: 90,
        tempo: '3-1-1-0',
        equipment: 'Heavy Dumbbell',
        formCues: [
          'Hold dumbbell vertically against upper sternum',
          'Slight heel elevation allows deeper knee flexion while keeping torso upright',
          'Drive through mid-foot and spread the floor on the ascent',
        ],
        substitutions: ['Barbell Front Squat', 'Dumbbell Bulgarian Split Squat'],
        safetyWarning: 'Keep knees tracking directly in line with second toes; avoid valgus knee cave.',
      },
      {
        id: 'd2-ex2',
        name: 'Romanian Deadlift (RDL)',
        targetMuscles: ['Hamstrings', 'Gluteus Maximus', 'Erector Spinae'],
        sets: 3,
        reps: '10-12',
        restSeconds: 90,
        tempo: '3-1-1-0',
        equipment: 'Dumbbells or Barbell',
        formCues: [
          'Hips push back horizontally as if closing a car door with glutes',
          'Shins remain perpendicular to floor; soft unlock at knees',
          'Lower dumbbells just below kneecaps until deep hamstring stretch is felt',
        ],
        substitutions: ['Single-Leg Dumbbell RDL', 'Barbell Good Mornings'],
        safetyWarning: 'Neutral spine is non-negotiable; do not round thoracic or lumbar spine.',
      },
      {
        id: 'd2-ex3',
        name: 'Dumbbell Walking Lunges',
        targetMuscles: ['Glutes', 'Hamstrings', 'Quadriceps'],
        sets: 3,
        reps: '10 per leg',
        restSeconds: 60,
        tempo: '2-0-1-0',
        equipment: 'Dumbbells',
        formCues: ['Take generous step forward with 90-degree bend in both knees', 'Trailing knee hovers 1 inch above floor'],
        substitutions: ['Reverse Lunges', 'Step-Ups onto Bench'],
      },
      {
        id: 'd2-ex4',
        name: 'Standing Single-Leg Dumbbell Calf Raises',
        targetMuscles: ['Gastrocnemius', 'Soleus'],
        sets: 3,
        reps: '15',
        restSeconds: 45,
        tempo: '2-1-1-1',
        equipment: 'Dumbbell & Step/Platform',
        formCues: ['2-second deep stretch at bottom, 1-second hard squeeze at peak contraction'],
        substitutions: ['Seated Calf Raise', 'Bodyweight Calf Burnout'],
      },
    ],
  },
  {
    dayNumber: 3,
    dayName: 'Day 3 - Active Recovery & Core Mobility',
    title: 'Kinetic Chain Recovery & Lumbar Stability',
    focusArea: 'Transverse Abdominis, Hip Flexor Mobility, Thoracic Extension',
    estimatedDurationMinutes: 30,
    difficulty: 'Beginner',
    isRestDay: true,
    warmUp: DEFAULT_WARMUP,
    coolDown: DEFAULT_COOLDOWN,
    exercises: [
      {
        id: 'd3-ex1',
        name: 'Dead Bug with Alternating Reach',
        targetMuscles: ['Transverse Abdominis', 'Internal/External Obliques'],
        sets: 3,
        reps: '10 per side',
        restSeconds: 45,
        tempo: '3-1-3-0',
        equipment: 'Mat (Bodyweight)',
        formCues: ['Press lower back firmly into floor—zero arching gap', 'Exhale fully as opposite arm and leg extend'],
        substitutions: ['Bird Dog', 'Hollow Body Hold'],
      },
      {
        id: 'd3-ex2',
        name: 'Side Plank with Top-Leg Pulse',
        targetMuscles: ['Quadratus Lumborum', 'Obliques', 'Gluteus Medius'],
        sets: 3,
        reps: '30s hold / side',
        restSeconds: 45,
        equipment: 'Bodyweight',
        formCues: ['Elbow directly below shoulder', 'Hips elevated in a laser-straight line'],
        substitutions: ['Kneeling Side Plank', 'Standard Forearm Plank'],
      },
      {
        id: 'd3-ex3',
        name: '90/90 Hip Flow & Shin Box Rotations',
        targetMuscles: ['Hip Internal & External Rotators'],
        sets: 3,
        reps: '8 rotations per side',
        restSeconds: 45,
        equipment: 'Mat',
        formCues: ['Sit tall without leaning excessively backward', 'Rotate knees smoothly through active range'],
        substitutions: ['Pigeon Stretch', 'Butterfly Groin Stretch'],
      },
      {
        id: 'd3-ex4',
        name: 'Thoracic Foam Rolling & Cat-Cow Waves',
        targetMuscles: ['Thoracic Spine', 'Erector Spinae'],
        sets: 3,
        reps: '10 wave cycles',
        restSeconds: 45,
        equipment: 'Foam Roller or Mat',
        formCues: ['Inhale to expand belly and drop sternum, exhale to tuck chin and dome upper back'],
        substitutions: ['Child’s Pose to Cobra', 'Thread the Needle'],
      },
    ],
  },
  {
    dayNumber: 4,
    dayName: 'Day 4 - Upper Body Pull & Posterior Delts',
    title: 'Back Width, Scapular Retraction & Biceps',
    focusArea: 'Latissimus Dorsi, Rhomboids, Trapezius, Biceps Brachii',
    estimatedDurationMinutes: 45,
    difficulty: 'Moderate',
    isRestDay: false,
    warmUp: DEFAULT_WARMUP.slice(0, 2),
    coolDown: DEFAULT_COOLDOWN.slice(0, 2),
    exercises: [
      {
        id: 'd4-ex1',
        name: 'Neutral-Grip Pull-ups (or Band-Assisted)',
        targetMuscles: ['Latissimus Dorsi', 'Teres Major', 'Biceps'],
        sets: 3,
        reps: '6-8',
        restSeconds: 90,
        tempo: '3-0-1-0',
        equipment: 'Pull-up Bar & Loop Resistance Band',
        formCues: [
          'Neutral palms facing inward minimizes stress on shoulder labrum',
          'Initiate movement by driving shoulder blades down before bending elbows',
          'Pull chest up toward bar; avoid shrugging',
        ],
        substitutions: ['Lat Pulldowns', 'Inverted Bodyweight Rows on Bar'],
      },
      {
        id: 'd4-ex2',
        name: 'Chest-Supported Dumbbell Rows',
        targetMuscles: ['Rhomboids', 'Mid Trapezius', 'Lats'],
        sets: 3,
        reps: '10-12',
        restSeconds: 75,
        tempo: '3-1-1-0',
        equipment: 'Dumbbells & Incline Bench',
        formCues: [
          'Chest anchored against bench eliminates lower back momentum',
          'Drive elbows back toward hips, squeezing shoulder blades together for 1 second',
        ],
        substitutions: ['Single-Arm Dumbbell Row', 'Barbell Bent-Over Row'],
      },
      {
        id: 'd4-ex3',
        name: 'Rear Delt Dumbbell Flyes (Prone Incline)',
        targetMuscles: ['Posterior Deltoids', 'Infraspinatus'],
        sets: 3,
        reps: '12-15',
        restSeconds: 60,
        tempo: '2-1-1-0',
        equipment: 'Light Dumbbells & Bench',
        formCues: ['Lead with pinkies to maximize rear deltoid recruitment', 'Hold peak contraction for 1 second'],
        substitutions: ['Face Pulls with Band', 'Reverse Pec Deck'],
      },
      {
        id: 'd4-ex4',
        name: 'Incline Dumbbell Bicep Curls',
        targetMuscles: ['Biceps Brachii Long Head'],
        sets: 3,
        reps: '10-12',
        restSeconds: 60,
        tempo: '3-0-1-0',
        equipment: 'Dumbbells & Bench',
        formCues: ['Elbows remain anchored behind torso for intense long head stretch', 'Full supination at top of curl'],
        substitutions: ['Standing Hammer Curls', 'Barbell Bicep Curls'],
      },
    ],
  },
  {
    dayNumber: 5,
    dayName: 'Day 5 - Glutes, Hamstrings & Unilateral Legs',
    title: 'Posterior Hypertrophy & Unilateral Balance',
    focusArea: 'Gluteus Medius, Hamstrings, Adductors, Core',
    estimatedDurationMinutes: 45,
    difficulty: 'Challenging',
    isRestDay: false,
    warmUp: DEFAULT_WARMUP.slice(1, 3),
    coolDown: DEFAULT_COOLDOWN.slice(1, 3),
    exercises: [
      {
        id: 'd5-ex1',
        name: 'Barbell or Dumbbell Hip Thrusts',
        targetMuscles: ['Gluteus Maximus', 'Hamstrings'],
        sets: 3,
        reps: '10-12',
        restSeconds: 90,
        tempo: '2-1-1-1',
        equipment: 'Bench & Barbell/Dumbbell',
        formCues: [
          'Shoulder blades pinned across bench pad, chin tucked toward chest',
          'Drive through heels until hips reach full extension parallel to floor',
          'Full glute contraction at top without hyper-arching lumbar spine',
        ],
        substitutions: ['Single-Leg Glute Bridge', 'Cable Pull-Throughs'],
      },
      {
        id: 'd5-ex2',
        name: 'Bulgarian Split Squat',
        targetMuscles: ['Quadriceps', 'Glutes', 'Adductors'],
        sets: 3,
        reps: '8-10 per leg',
        restSeconds: 75,
        tempo: '3-1-1-0',
        equipment: 'Dumbbells & Bench',
        formCues: [
          'Rear foot laces resting comfortably on bench',
          'Descend under control until front thigh is parallel to floor',
          'Keep torso inclined slightly forward to load gluteus maximus',
        ],
        substitutions: ['Reverse Lunge from Step', 'Goblet Squat'],
      },
      {
        id: 'd5-ex3',
        name: 'Swiss Ball or Slider Hamstring Curls',
        targetMuscles: ['Hamstrings', 'Calves'],
        sets: 3,
        reps: '12',
        restSeconds: 60,
        tempo: '2-1-1-0',
        equipment: 'Stability Ball or Towel on Smooth Floor',
        formCues: ['Bridge hips up and pull heels toward glutes in one smooth motion', 'Lower back remains stable'],
        substitutions: ['Dumbbell Lying Leg Curl', 'Nordic Hamstring Curl'],
      },
      {
        id: 'd5-ex4',
        name: 'Standing Dumbbell Farmer Walks',
        targetMuscles: ['Forearms', 'Trapezius', 'Core Stability'],
        sets: 3,
        reps: '40 meters',
        restSeconds: 60,
        equipment: 'Two Heavy Dumbbells',
        formCues: ['Shoulders pinned down and back', 'Walk in disciplined heel-to-toe stride without swaying'],
        substitutions: ['Suitcase Carry (Single-Arm)', 'Plank Hold for 60s'],
      },
    ],
  },
  {
    dayNumber: 6,
    dayName: 'Day 6 - Full Body Metabolic Conditioning',
    title: 'Aerobic Power & High-Yield Hybrid Circuits',
    focusArea: 'Cardiovascular Conditioning, Full Body Stamina, Core',
    estimatedDurationMinutes: 40,
    difficulty: 'High Intensity',
    isRestDay: false,
    warmUp: DEFAULT_WARMUP,
    coolDown: DEFAULT_COOLDOWN,
    exercises: [
      {
        id: 'd6-ex1',
        name: 'Dumbbell Clean & Push Press',
        targetMuscles: ['Shoulders', 'Glutes', 'Hamstrings', 'Triceps'],
        sets: 4,
        reps: '8 reps',
        restSeconds: 60,
        tempo: 'Explosive',
        equipment: 'Dumbbells',
        formCues: ['Dip hips and catch dumbbells at shoulders, immediately drive overhead with leg power'],
        substitutions: ['Kettlebell Swings', 'Dumbbell Thrusters'],
      },
      {
        id: 'd6-ex2',
        name: 'Renegade Rows to Push-up',
        targetMuscles: ['Lats', 'Chest', 'Core Obliques'],
        sets: 3,
        reps: '6-8 combos',
        restSeconds: 60,
        tempo: 'Controlled',
        equipment: 'Pair of Hex Dumbbells',
        formCues: ['Feet set shoulder-width apart to prevent hip sway during row'],
        substitutions: ['Push-up with Hand Tap', 'Single-Arm Dumbbell Plank Row'],
      },
      {
        id: 'd6-ex3',
        name: 'Kettlebell or Dumbbell Goblet Speed Squats',
        targetMuscles: ['Quadriceps', 'Glutes', 'Lungs'],
        sets: 3,
        reps: '15 reps',
        restSeconds: 45,
        tempo: '1-0-1-0',
        equipment: 'Dumbbell',
        formCues: ['Rhythmic continuous movement with pristine depth and upright chest'],
        substitutions: ['Jump Squats', 'Wall Sit for 45s'],
      },
      {
        id: 'd6-ex4',
        name: 'Hanging Knee Raises / Reverse Crunches',
        targetMuscles: ['Rectus Abdominis', 'Hip Flexors'],
        sets: 3,
        reps: '12-15',
        restSeconds: 45,
        tempo: '2-1-2-0',
        equipment: 'Pull-up Bar or Mat',
        formCues: ['Roll pelvis upward to curl bottom ribs toward hips; do not swing body'],
        substitutions: ['Ab Wheel Rollout', 'Bicycle Crunches'],
      },
    ],
  },
  {
    dayNumber: 7,
    dayName: 'Day 7 - Rest, Hydration & Neural Decompression',
    title: 'Parasympathetic Recovery & Meal Prep Day',
    focusArea: 'Central Nervous System, Fascial Hydration, Restorative Sleep',
    estimatedDurationMinutes: 20,
    difficulty: 'Beginner',
    isRestDay: true,
    warmUp: DEFAULT_WARMUP.slice(0, 2),
    coolDown: DEFAULT_COOLDOWN,
    exercises: [
      {
        id: 'd7-ex1',
        name: '30-Minute Outdoor Nature Walk (Zone 1)',
        targetMuscles: ['Cardiovascular System', 'Lymphatic Flow'],
        sets: 1,
        reps: '30-40 min',
        restSeconds: 0,
        equipment: 'Walking Shoes',
        formCues: ['Brisk casual pace where nasal breathing is comfortable', 'Aids lactate clearance and lowers cortisol'],
        substitutions: ['Gentle Stationary Bike Spin', 'Pool Walking'],
      },
      {
        id: 'd7-ex2',
        name: 'Full Body Foam Rolling & Trigger Point Release',
        targetMuscles: ['IT Bands', 'Lats', 'Calves', 'Thoracic Spine'],
        sets: 1,
        reps: '10 min total',
        restSeconds: 0,
        equipment: 'Foam Roller & Lacrosse Ball',
        formCues: ['Roll slowly over tight tissue; pause 20 seconds on tender trigger spots and breathe deeply'],
        substitutions: ['Stretching Session', 'Warm Epsom Salt Bath'],
      },
    ],
  },
];

export const INITIAL_FITNESS_PLAN: FitnessPlan = {
  id: 'plan-starter-default',
  userId: 'user-default',
  version: 1,
  isOriginal: true,
  createdAt: new Date().toISOString(),
  planTitle: 'Titan 7-Day Hypertrophy & Kinetic Conditioning Architecture',
  tagline: 'Sculpt lean muscle, boost metabolic conditioning, and fortify joint durability across a structured 7-day split.',
  planOverview:
    'A high-yield 7-day training schedule engineered to optimize muscle protein synthesis with balanced push/pull volume, compound multi-joint movements, dedicated kinetic core stability, and deliberate active recovery periods.',
  weeklyFocus: 'Time-under-tension discipline (3-second eccentric tempo) and shoulder blade retraction mechanics.',
  workoutIntensity: 'moderate',
  quickNutritionRecoveryTip:
    'Consume 35-40g high-quality whey isolate or lean poultry with 60g complex carbs within 45 minutes of lifting, and drink 3.2L water with trace electrolytes.',
  userProfileSnapshot: DEFAULT_USER_PROFILE,
  generalWarmUp: DEFAULT_WARMUP,
  generalCoolDown: DEFAULT_COOLDOWN,
  days: SEVEN_DAYS_WORKOUTS,
  nutritionPlan: {
    dailyCalorieTarget: 2650,
    calorieGoalType: 'Surplus (+300 kcal)',
    macroBreakdown: {
      proteinGrams: 165,
      carbsGrams: 310,
      fatsGrams: 70,
    },
    hydrationLiters: 3.2,
    preWorkoutAdvice:
      'Consume 30-40g easy-digesting complex carbohydrates + 20g whey/plant protein 60 to 90 minutes before lifting (e.g. oatmeal with scoop of protein and half a banana). Drink 500ml water.',
    postWorkoutAdvice:
      'Within 45 minutes of training completion, consume 30-40g fast-acting protein with 50-70g carbohydrates to halt muscle protein breakdown and replenish glycogen reserves.',
    sampleMeals: [
      {
        mealType: 'Power Breakfast',
        name: 'Supercharged Oatmeal Bowl with Berries & Whey',
        calories: 580,
        proteinGrams: 42,
        description:
          'Rolled oats simmered in unsweetened almond milk, folded with vanilla whey isolate, topped with fresh blueberries, chia seeds, and 1 tbsp almond butter.',
        keyIngredients: ['Rolled oats (80g)', 'Whey isolate (35g)', 'Blueberries (75g)', 'Chia seeds', 'Almond butter (16g)'],
      },
      {
        mealType: 'Pre-Workout Fuel',
        name: 'Whole Grain Toast with Banana & Cinnamon Honey',
        calories: 320,
        proteinGrams: 10,
        description: 'Sourdough or sprouted grain toast spread with light peanut butter, sliced banana, and dash of cinnamon for insulin sensitivity.',
        keyIngredients: ['Sprouted grain bread (2 slices)', 'Peanut butter (15g)', 'Banana', 'Ceylon cinnamon'],
      },
      {
        mealType: 'Post-Workout Anabolic Lunch',
        name: 'Charred Citrus Grilled Chicken & Quinoa Harvest Bowl',
        calories: 720,
        proteinGrams: 52,
        description:
          'Marinated chicken breast atop fluffy tri-color quinoa, roasted sweet potato cubes, steamed broccoli florets, and light tahini lemon dressing.',
        keyIngredients: ['Chicken breast (200g)', 'Cooked quinoa (180g)', 'Roasted sweet potato (150g)', 'Broccoli (120g)', 'Tahini lemon vinaigrette'],
      },
      {
        mealType: 'Recovery Dinner & Night Fuel',
        name: 'Pan-Seared Wild Salmon with Jasmine Rice & Asparagus',
        calories: 680,
        proteinGrams: 45,
        description:
          'Wild-caught salmon fillet rich in Omega-3 anti-inflammatory fatty acids, paired with fragrant jasmine rice and garlic sautéed asparagus spears.',
        keyIngredients: ['Wild salmon fillet (180g)', 'Jasmine rice (200g cooked)', 'Fresh asparagus spears', 'Extra virgin olive oil', 'Lemon slice'],
      },
    ],
    hydrationTips: [
      'Drink 500ml of water immediately upon waking to counter overnight respiratory fluid loss.',
      'Add a pinch of sea salt or an electrolyte packet into your training bottle if sweating heavily.',
      'Monitor urine color: aim for pale straw color rather than crystal clear or dark yellow.',
    ],
  },
  safetyGuidelines: [
    {
      topic: 'Shoulder Impingement Protocol',
      guideline:
        'When performing overhead or bench press variations, always maintain a 45-degree elbow tuck rather than flaring elbows perpendicular to torso. Avoid any pressing movements behind the neck.',
      importance: 'Injury Prevention',
    },
    {
      topic: 'Progressive Overload & RPE Tracking',
      guideline:
        'Aim to finish working sets with 1 to 2 reps in reserve (RPE 8-8.5). When you hit the top of the recommended rep bracket with pristine technique across all sets, increase load by 2.5% - 5%.',
      importance: 'Essential',
    },
    {
      topic: 'Warm-up Set Ramp',
      guideline:
        'Never jump directly into your working weights on compound movements (Squats, Presses, RDLs). Perform 2-3 specific warm-up ramp sets with 40%, 60%, and 80% load with low reps.',
      importance: 'Form Priority',
    },
    {
      topic: 'Eccentric Control Discipline',
      guideline:
        'Lower every weight under conscious 3-second tension control. Muscle micro-tears and hypertrophy stimulus happen during the eccentric phase, which also protects tendons.',
      importance: 'Essential',
    },
  ],
};

export const INITIAL_WORKOUT_LOGS: WorkoutHistoryLog[] = [
  {
    id: 'log-1',
    planId: 'plan-starter-default',
    dayNumber: 1,
    dayTitle: 'Upper Body Push & Strength',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    durationMinutes: 44,
    exercisesCompleted: [
      {
        exerciseName: 'Incline Dumbbell Bench Press',
        sets: [
          { setNumber: 1, weightKg: 24, repsCompleted: 10 },
          { setNumber: 2, weightKg: 26, repsCompleted: 9 },
          { setNumber: 3, weightKg: 26, repsCompleted: 8 },
        ],
      },
      {
        exerciseName: 'Standing Dumbbell Overhead Press',
        sets: [
          { setNumber: 1, weightKg: 14, repsCompleted: 12 },
          { setNumber: 2, weightKg: 16, repsCompleted: 10 },
          { setNumber: 3, weightKg: 16, repsCompleted: 10 },
        ],
      },
    ],
    rpeRating: 8,
    energyLevel: 'Great',
    notes: 'Shoulder felt solid with the neutral incline angle. Felt good mind-muscle connection.',
  },
  {
    id: 'log-2',
    planId: 'plan-starter-default',
    dayNumber: 2,
    dayTitle: 'Lower Body Quad & Posterior Chain',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    durationMinutes: 47,
    exercisesCompleted: [
      {
        exerciseName: 'Goblet Squat',
        sets: [
          { setNumber: 1, weightKg: 32, repsCompleted: 10 },
          { setNumber: 2, weightKg: 36, repsCompleted: 10 },
          { setNumber: 3, weightKg: 36, repsCompleted: 8 },
        ],
      },
      {
        exerciseName: 'Romanian Deadlift (RDL)',
        sets: [
          { setNumber: 1, weightKg: 28, repsCompleted: 12 },
          { setNumber: 2, weightKg: 30, repsCompleted: 10 },
          { setNumber: 3, weightKg: 30, repsCompleted: 10 },
        ],
      },
    ],
    rpeRating: 8.5,
    energyLevel: 'Peak',
    notes: 'Solid hamstring recruitment on RDLs. Kept spine braced tight.',
  },
];
